name: vehtrajpred
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - asttokens=2.2.1=pyhd8ed1ab_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=pyhd8ed1ab_3
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2023.5.7=hbcca054_0
  - debugpy=1.5.1=py310h295c915_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - executing=1.2.0=pyhd8ed1ab_0
  - ipykernel=6.15.0=pyh210e3f2_0
  - ipython=8.14.0=pyh41d4057_0
  - jedi=0.18.2=pyhd8ed1ab_0
  - jupyter_client=7.3.4=pyhd8ed1ab_0
  - jupyter_core=5.3.0=py310hff52083_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libsodium=1.0.18=h36c2ea0_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.5.6=pyhd8ed1ab_0
  - openssl=1.1.1t=h7f8727e_0
  - packaging=23.1=pyhd8ed1ab_0
  - parso=0.8.3=pyhd8ed1ab_0
  - pexpect=4.8.0=pyh1a96a4e_2
  - pickleshare=0.7.5=py_1003
  - pip=23.0.1=py310h06a4308_0
  - platformdirs=3.5.3=pyhd8ed1ab_0
  - prompt-toolkit=3.0.38=pyha770c72_0
  - prompt_toolkit=3.0.38=hd8ed1ab_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pygments=2.15.1=pyhd8ed1ab_0
  - python=3.10.9=h7a1cb2a_2
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.10=2_cp310
  - pyzmq=25.0.2=py310h6a678d5_0
  - readline=8.2=h5eee18b_0
  - setuptools=67.8.0=py310h06a4308_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.41.2=h5eee18b_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - tk=8.6.12=h1ccaba5_0
  - tornado=6.1=py310h5764c6d_3
  - traitlets=5.9.0=pyhd8ed1ab_0
  - typing-extensions=4.6.3=hd8ed1ab_0
  - typing_extensions=4.6.3=pyha770c72_0
  - wcwidth=0.2.6=pyhd8ed1ab_0
  - wheel=0.38.4=py310h06a4308_0
  - xz=5.4.2=h5eee18b_0
  - zeromq=4.3.4=h9c3ff4c_1
  - zlib=1.2.13=h5eee18b_0
  - pip:
      - absl-py==1.4.0
      - astunparse==1.6.3
      - beautifulsoup4==4.12.2
      - cachetools==5.3.1
      - certifi==2023.5.7
      - charset-normalizer==3.1.0
      - cmake==3.26.4
      - contourpy==1.0.7
      - cycler==0.11.0
      - filelock==3.12.0
      - flatbuffers==23.5.26
      - fonttools==4.39.4
      - gast==0.4.0
      - gdown==4.7.1
      - google-auth==2.19.1
      - google-auth-oauthlib==1.0.0
      - google-pasta==0.2.0
      - grpcio==1.54.2
      - h5py==3.8.0
      - idna==3.4
      - jax==0.4.12
      - jinja2==3.1.2
      - keras==2.12.0
      - kiwisolver==1.4.4
      - libclang==16.0.0
      - lit==16.0.5.post0
      - markdown==3.4.3
      - markupsafe==2.1.3
      - matplotlib==3.7.1
      - ml-dtypes==0.2.0
      - mpmath==1.3.0
      - networkx==3.1
      - numpy==1.23.5
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cuda-cupti-cu11==11.7.101
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cudnn-cu11==8.5.0.96
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.2.10.91
      - nvidia-cusolver-cu11==11.4.0.1
      - nvidia-cusparse-cu11==11.7.4.91
      - nvidia-nccl-cu11==2.14.3
      - nvidia-nvtx-cu11==11.7.91
      - oauthlib==3.2.2
      - opencv-python==4.7.0.72
      - opt-einsum==3.3.0
      - pandas==2.0.2
      - pillow==9.5.0
      - protobuf==4.23.2
      - psutil==5.9.5
      - pyasn1==0.5.0
      - pyasn1-modules==0.3.0
      - pyparsing==3.0.9
      - pysocks==1.7.1
      - pytube==15.0.0
      - pytz==2023.3
      - pyyaml==6.0
      - requests==2.31.0
      - requests-oauthlib==1.3.1
      - rsa==4.9
      - scipy==1.10.1
      - seaborn==0.12.2
      - soupsieve==2.4.1
      - sympy==1.12
      - tensorboard==2.12.3
      - tensorboard-data-server==0.7.0
      - tensorflow==2.12.0
      - tensorflow-estimator==2.12.0
      - tensorflow-io-gcs-filesystem==0.32.0
      - termcolor==2.3.0
      - thop==0.1.1-2209072238
      - torch==2.0.1
      - torchvision==0.15.2
      - tqdm==4.65.0
      - triton==2.0.0
      - tzdata==2023.3
      - urllib3==1.26.16
      - werkzeug==2.3.6
      - wrapt==1.14.1
prefix: /home/tomato/miniconda3/envs/yolov7
